default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: patient_management_system_development

test:
  <<: *default
  database: patient_management_system_test

production:
  <<: *default
  database: patient_management_system_production
  username: patient_management_system
  password: <%= ENV['PATIENT_MANAGEMENT_DATABASE_PASSWORD'] %>
